/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const DonationEvent = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'bloodGroupsNeeded' : IDL.Vec(IDL.Text),
  'date' : Time,
  'currentRegistrations' : IDL.Nat,
  'hospitalId' : IDL.Principal,
  'maxRegistrations' : IDL.Nat,
  'location' : IDL.Text,
});
export const DonationNeed = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'trustId' : IDL.Principal,
  'needType' : IDL.Variant({
    'Clothes' : IDL.Null,
    'Money' : IDL.Null,
    'Essentials' : IDL.Null,
  }),
  'description' : IDL.Text,
  'receivedAmount' : IDL.Nat,
  'targetAmount' : IDL.Nat,
});
export const AppRole = IDL.Variant({
  'PublicUser' : IDL.Null,
  'Doctor' : IDL.Null,
  'Trust' : IDL.Null,
  'Admin' : IDL.Null,
  'Hospital' : IDL.Null,
});
export const VerificationStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'lastProfileUpdate' : Time,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : AppRole,
  'registrationNumber' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'hospitalId' : IDL.Opt(IDL.Principal),
  'aadharNumber' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'specialization' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'verificationStatus' : VerificationStatus,
});
export const DonationRegistration = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'eventId' : IDL.Text,
  'userId' : IDL.Principal,
  'registeredAt' : Time,
});
export const Contribution = IDL.Record({
  'id' : IDL.Text,
  'contributedAt' : Time,
  'userId' : IDL.Principal,
  'needId' : IDL.Text,
  'amount' : IDL.Nat,
  'contributionType' : IDL.Variant({
    'Clothes' : IDL.Null,
    'Money' : IDL.Null,
    'Essentials' : IDL.Null,
  }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveDoctorForHospital' : IDL.Func([IDL.Principal], [], []),
  'approveUser' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkCanUpdateProfile' : IDL.Func([], [IDL.Bool], ['query']),
  'contributeToNeed' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Variant({
          'Clothes' : IDL.Null,
          'Money' : IDL.Null,
          'Essentials' : IDL.Null,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'createDonationEvent' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), Time, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'createDonationNeed' : IDL.Func(
      [
        IDL.Variant({
          'Clothes' : IDL.Null,
          'Money' : IDL.Null,
          'Essentials' : IDL.Null,
        }),
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Text],
      [],
    ),
  'deleteDonationEvent' : IDL.Func([IDL.Text], [], []),
  'getAllDonationEvents' : IDL.Func([], [IDL.Vec(DonationEvent)], ['query']),
  'getAllDonationNeeds' : IDL.Func([], [IDL.Vec(DonationNeed)], ['query']),
  'getAllPendingVerifications' : IDL.Func(
      [],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoctorVerificationStatus' : IDL.Func([], [VerificationStatus], ['query']),
  'getHospitalMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEvents' : IDL.Nat,
          'activeEvents' : IDL.Nat,
          'totalRegistrations' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getHospitalRegistrations' : IDL.Func(
      [],
      [IDL.Vec(DonationRegistration)],
      ['query'],
    ),
  'getLivesSavedCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getNearbyEvents' : IDL.Func([IDL.Text], [IDL.Vec(DonationEvent)], ['query']),
  'getSystemAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'urgentNeeds' : IDL.Nat,
          'livesSaved' : IDL.Nat,
          'activePrograms' : IDL.Nat,
          'totalDonors' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTrustAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalContributions' : IDL.Nat,
          'totalAmountReceived' : IDL.Nat,
          'totalNeeds' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTrustContributions' : IDL.Func([], [IDL.Vec(Contribution)], ['query']),
  'getUrgentNeeds' : IDL.Func([], [IDL.Vec(DonationNeed)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listUsersByRole' : IDL.Func([AppRole], [IDL.Vec(UserProfile)], ['query']),
  'registerForDonationEvent' : IDL.Func([IDL.Text], [IDL.Text], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitDoctorVerification' : IDL.Func([IDL.Principal], [], []),
  'updateDonationEvent' : IDL.Func([IDL.Text, DonationEvent], [], []),
  'updateDonationNeed' : IDL.Func([IDL.Text, DonationNeed], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const DonationEvent = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'bloodGroupsNeeded' : IDL.Vec(IDL.Text),
    'date' : Time,
    'currentRegistrations' : IDL.Nat,
    'hospitalId' : IDL.Principal,
    'maxRegistrations' : IDL.Nat,
    'location' : IDL.Text,
  });
  const DonationNeed = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'trustId' : IDL.Principal,
    'needType' : IDL.Variant({
      'Clothes' : IDL.Null,
      'Money' : IDL.Null,
      'Essentials' : IDL.Null,
    }),
    'description' : IDL.Text,
    'receivedAmount' : IDL.Nat,
    'targetAmount' : IDL.Nat,
  });
  const AppRole = IDL.Variant({
    'PublicUser' : IDL.Null,
    'Doctor' : IDL.Null,
    'Trust' : IDL.Null,
    'Admin' : IDL.Null,
    'Hospital' : IDL.Null,
  });
  const VerificationStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'lastProfileUpdate' : Time,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : AppRole,
    'registrationNumber' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'hospitalId' : IDL.Opt(IDL.Principal),
    'aadharNumber' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'specialization' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'verificationStatus' : VerificationStatus,
  });
  const DonationRegistration = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'eventId' : IDL.Text,
    'userId' : IDL.Principal,
    'registeredAt' : Time,
  });
  const Contribution = IDL.Record({
    'id' : IDL.Text,
    'contributedAt' : Time,
    'userId' : IDL.Principal,
    'needId' : IDL.Text,
    'amount' : IDL.Nat,
    'contributionType' : IDL.Variant({
      'Clothes' : IDL.Null,
      'Money' : IDL.Null,
      'Essentials' : IDL.Null,
    }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveDoctorForHospital' : IDL.Func([IDL.Principal], [], []),
    'approveUser' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkCanUpdateProfile' : IDL.Func([], [IDL.Bool], ['query']),
    'contributeToNeed' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Variant({
            'Clothes' : IDL.Null,
            'Money' : IDL.Null,
            'Essentials' : IDL.Null,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'createDonationEvent' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), Time, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'createDonationNeed' : IDL.Func(
        [
          IDL.Variant({
            'Clothes' : IDL.Null,
            'Money' : IDL.Null,
            'Essentials' : IDL.Null,
          }),
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
    'deleteDonationEvent' : IDL.Func([IDL.Text], [], []),
    'getAllDonationEvents' : IDL.Func([], [IDL.Vec(DonationEvent)], ['query']),
    'getAllDonationNeeds' : IDL.Func([], [IDL.Vec(DonationNeed)], ['query']),
    'getAllPendingVerifications' : IDL.Func(
        [],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoctorVerificationStatus' : IDL.Func(
        [],
        [VerificationStatus],
        ['query'],
      ),
    'getHospitalMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEvents' : IDL.Nat,
            'activeEvents' : IDL.Nat,
            'totalRegistrations' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getHospitalRegistrations' : IDL.Func(
        [],
        [IDL.Vec(DonationRegistration)],
        ['query'],
      ),
    'getLivesSavedCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getNearbyEvents' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DonationEvent)],
        ['query'],
      ),
    'getSystemAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'urgentNeeds' : IDL.Nat,
            'livesSaved' : IDL.Nat,
            'activePrograms' : IDL.Nat,
            'totalDonors' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTrustAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalContributions' : IDL.Nat,
            'totalAmountReceived' : IDL.Nat,
            'totalNeeds' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTrustContributions' : IDL.Func([], [IDL.Vec(Contribution)], ['query']),
    'getUrgentNeeds' : IDL.Func([], [IDL.Vec(DonationNeed)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listUsersByRole' : IDL.Func([AppRole], [IDL.Vec(UserProfile)], ['query']),
    'registerForDonationEvent' : IDL.Func([IDL.Text], [IDL.Text], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitDoctorVerification' : IDL.Func([IDL.Principal], [], []),
    'updateDonationEvent' : IDL.Func([IDL.Text, DonationEvent], [], []),
    'updateDonationNeed' : IDL.Func([IDL.Text, DonationNeed], [], []),
  });
};

export const init = ({ IDL }) => { return []; };