/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'PublicUser' : null } |
  { 'Doctor' : null } |
  { 'Trust' : null } |
  { 'Admin' : null } |
  { 'Hospital' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Contribution {
  'id' : string,
  'contributedAt' : Time,
  'userId' : Principal,
  'needId' : string,
  'amount' : bigint,
  'contributionType' : { 'Clothes' : null } |
    { 'Money' : null } |
    { 'Essentials' : null },
}
export interface DonationEvent {
  'id' : string,
  'status' : string,
  'title' : string,
  'bloodGroupsNeeded' : Array<string>,
  'date' : Time,
  'currentRegistrations' : bigint,
  'hospitalId' : Principal,
  'maxRegistrations' : bigint,
  'location' : string,
}
export interface DonationNeed {
  'id' : string,
  'status' : string,
  'title' : string,
  'trustId' : Principal,
  'needType' : { 'Clothes' : null } |
    { 'Money' : null } |
    { 'Essentials' : null },
  'description' : string,
  'receivedAmount' : bigint,
  'targetAmount' : bigint,
}
export interface DonationRegistration {
  'id' : string,
  'status' : string,
  'eventId' : string,
  'userId' : Principal,
  'registeredAt' : Time,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'id' : Principal,
  'bio' : string,
  'lastProfileUpdate' : Time,
  'name' : string,
  'createdAt' : Time,
  'role' : AppRole,
  'registrationNumber' : [] | [string],
  'email' : string,
  'hospitalId' : [] | [Principal],
  'aadharNumber' : [] | [string],
  'address' : string,
  'specialization' : [] | [string],
  'phone' : string,
  'verificationStatus' : VerificationStatus,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerificationStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveDoctorForHospital' : ActorMethod<[Principal], undefined>,
  'approveUser' : ActorMethod<[Principal, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkCanUpdateProfile' : ActorMethod<[], boolean>,
  'contributeToNeed' : ActorMethod<
    [
      string,
      bigint,
      { 'Clothes' : null } |
        { 'Money' : null } |
        { 'Essentials' : null },
    ],
    string
  >,
  'createDonationEvent' : ActorMethod<
    [string, Array<string>, Time, string, bigint],
    string
  >,
  'createDonationNeed' : ActorMethod<
    [
      { 'Clothes' : null } |
        { 'Money' : null } |
        { 'Essentials' : null },
      string,
      string,
      bigint,
    ],
    string
  >,
  'deleteDonationEvent' : ActorMethod<[string], undefined>,
  'getAllDonationEvents' : ActorMethod<[], Array<DonationEvent>>,
  'getAllDonationNeeds' : ActorMethod<[], Array<DonationNeed>>,
  'getAllPendingVerifications' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoctorVerificationStatus' : ActorMethod<[], VerificationStatus>,
  'getHospitalMetrics' : ActorMethod<
    [],
    {
      'totalEvents' : bigint,
      'activeEvents' : bigint,
      'totalRegistrations' : bigint,
    }
  >,
  'getHospitalRegistrations' : ActorMethod<[], Array<DonationRegistration>>,
  'getLivesSavedCount' : ActorMethod<[], bigint>,
  'getNearbyEvents' : ActorMethod<[string], Array<DonationEvent>>,
  'getSystemAnalytics' : ActorMethod<
    [],
    {
      'urgentNeeds' : bigint,
      'livesSaved' : bigint,
      'activePrograms' : bigint,
      'totalDonors' : bigint,
    }
  >,
  'getTrustAnalytics' : ActorMethod<
    [],
    {
      'totalContributions' : bigint,
      'totalAmountReceived' : bigint,
      'totalNeeds' : bigint,
    }
  >,
  'getTrustContributions' : ActorMethod<[], Array<Contribution>>,
  'getUrgentNeeds' : ActorMethod<[], Array<DonationNeed>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listUsersByRole' : ActorMethod<[AppRole], Array<UserProfile>>,
  'registerForDonationEvent' : ActorMethod<[string], string>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitDoctorVerification' : ActorMethod<[Principal], undefined>,
  'updateDonationEvent' : ActorMethod<[string, DonationEvent], undefined>,
  'updateDonationNeed' : ActorMethod<[string, DonationNeed], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];