/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export type Time = bigint;
export interface DonationRegistration {
    id: string;
    status: string;
    eventId: string;
    userId: Principal;
    registeredAt: Time;
}
export interface DonationNeed {
    id: string;
    status: string;
    title: string;
    trustId: Principal;
    needType: Variant_Clothes_Money_Essentials;
    description: string;
    receivedAmount: bigint;
    targetAmount: bigint;
}
export interface DonationEvent {
    id: string;
    status: string;
    title: string;
    bloodGroupsNeeded: Array<string>;
    date: Time;
    currentRegistrations: bigint;
    hospitalId: Principal;
    maxRegistrations: bigint;
    location: string;
}
export interface Contribution {
    id: string;
    contributedAt: Time;
    userId: Principal;
    needId: string;
    amount: bigint;
    contributionType: Variant_Clothes_Money_Essentials;
}
export interface UserProfile {
    id: Principal;
    bio: string;
    lastProfileUpdate: Time;
    name: string;
    createdAt: Time;
    role: AppRole;
    registrationNumber?: string;
    email: string;
    hospitalId?: Principal;
    aadharNumber?: string;
    address: string;
    specialization?: string;
    phone: string;
    verificationStatus: VerificationStatus;
}
export enum AppRole {
    PublicUser = "PublicUser",
    Doctor = "Doctor",
    Trust = "Trust",
    Admin = "Admin",
    Hospital = "Hospital"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_Clothes_Money_Essentials {
    Clothes = "Clothes",
    Money = "Money",
    Essentials = "Essentials"
}
export enum VerificationStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveDoctorForHospital(doctorId: Principal): Promise<void>;
    approveUser(userId: Principal, approved: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkCanUpdateProfile(): Promise<boolean>;
    contributeToNeed(needId: string, amount: bigint, contributionType: Variant_Clothes_Money_Essentials): Promise<string>;
    createDonationEvent(title: string, bloodGroupsNeeded: Array<string>, date: Time, location: string, maxRegistrations: bigint): Promise<string>;
    createDonationNeed(needType: Variant_Clothes_Money_Essentials, title: string, description: string, targetAmount: bigint): Promise<string>;
    deleteDonationEvent(eventId: string): Promise<void>;
    getAllDonationEvents(): Promise<Array<DonationEvent>>;
    getAllDonationNeeds(): Promise<Array<DonationNeed>>;
    getAllPendingVerifications(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDoctorVerificationStatus(): Promise<VerificationStatus>;
    getHospitalMetrics(): Promise<{
        totalEvents: bigint;
        activeEvents: bigint;
        totalRegistrations: bigint;
    }>;
    getHospitalRegistrations(): Promise<Array<DonationRegistration>>;
    getLivesSavedCount(): Promise<bigint>;
    getNearbyEvents(location: string): Promise<Array<DonationEvent>>;
    getSystemAnalytics(): Promise<{
        urgentNeeds: bigint;
        livesSaved: bigint;
        activePrograms: bigint;
        totalDonors: bigint;
    }>;
    getTrustAnalytics(): Promise<{
        totalContributions: bigint;
        totalAmountReceived: bigint;
        totalNeeds: bigint;
    }>;
    getTrustContributions(): Promise<Array<Contribution>>;
    getUrgentNeeds(): Promise<Array<DonationNeed>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listUsersByRole(role: AppRole): Promise<Array<UserProfile>>;
    registerForDonationEvent(eventId: string): Promise<string>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    submitDoctorVerification(hospitalId: Principal): Promise<void>;
    updateDonationEvent(eventId: string, event: DonationEvent): Promise<void>;
    updateDonationNeed(needId: string, need: DonationNeed): Promise<void>;
}
import type { AppRole as _AppRole, ApprovalStatus as _ApprovalStatus, Contribution as _Contribution, DonationNeed as _DonationNeed, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, VerificationStatus as _VerificationStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveDoctorForHospital(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDoctorForHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDoctorForHospital(arg0);
            return result;
        }
    }
    async approveUser(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUser(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkCanUpdateProfile(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkCanUpdateProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkCanUpdateProfile();
            return result;
        }
    }
    async contributeToNeed(arg0: string, arg1: bigint, arg2: Variant_Clothes_Money_Essentials): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.contributeToNeed(arg0, arg1, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.contributeToNeed(arg0, arg1, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createDonationEvent(arg0: string, arg1: Array<string>, arg2: Time, arg3: string, arg4: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDonationEvent(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDonationEvent(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createDonationNeed(arg0: Variant_Clothes_Money_Essentials, arg1: string, arg2: string, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDonationNeed(to_candid_variant_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDonationNeed(to_candid_variant_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async deleteDonationEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDonationEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDonationEvent(arg0);
            return result;
        }
    }
    async getAllDonationEvents(): Promise<Array<DonationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonationEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonationEvents();
            return result;
        }
    }
    async getAllDonationNeeds(): Promise<Array<DonationNeed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonationNeeds();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonationNeeds();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingVerifications(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingVerifications();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingVerifications();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorVerificationStatus(): Promise<VerificationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorVerificationStatus();
                return from_candid_VerificationStatus_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorVerificationStatus();
            return from_candid_VerificationStatus_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHospitalMetrics(): Promise<{
        totalEvents: bigint;
        activeEvents: bigint;
        totalRegistrations: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitalMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitalMetrics();
            return result;
        }
    }
    async getHospitalRegistrations(): Promise<Array<DonationRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitalRegistrations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitalRegistrations();
            return result;
        }
    }
    async getLivesSavedCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLivesSavedCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLivesSavedCount();
            return result;
        }
    }
    async getNearbyEvents(arg0: string): Promise<Array<DonationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbyEvents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbyEvents(arg0);
            return result;
        }
    }
    async getSystemAnalytics(): Promise<{
        urgentNeeds: bigint;
        livesSaved: bigint;
        activePrograms: bigint;
        totalDonors: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemAnalytics();
            return result;
        }
    }
    async getTrustAnalytics(): Promise<{
        totalContributions: bigint;
        totalAmountReceived: bigint;
        totalNeeds: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrustAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrustAnalytics();
            return result;
        }
    }
    async getTrustContributions(): Promise<Array<Contribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrustContributions();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrustContributions();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUrgentNeeds(): Promise<Array<DonationNeed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUrgentNeeds();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUrgentNeeds();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsersByRole(arg0: AppRole): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsersByRole(to_candid_AppRole_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsersByRole(to_candid_AppRole_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerForDonationEvent(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerForDonationEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerForDonationEvent(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitDoctorVerification(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDoctorVerification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDoctorVerification(arg0);
            return result;
        }
    }
    async updateDonationEvent(arg0: string, arg1: DonationEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonationEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonationEvent(arg0, arg1);
            return result;
        }
    }
    async updateDonationNeed(arg0: string, arg1: DonationNeed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonationNeed(arg0, to_candid_DonationNeed_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonationNeed(arg0, to_candid_DonationNeed_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AppRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Contribution_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contribution): Contribution {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_DonationNeed_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationNeed): DonationNeed {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: string;
    lastProfileUpdate: _Time;
    name: string;
    createdAt: _Time;
    role: _AppRole;
    registrationNumber: [] | [string];
    email: string;
    hospitalId: [] | [Principal];
    aadharNumber: [] | [string];
    address: string;
    specialization: [] | [string];
    phone: string;
    verificationStatus: _VerificationStatus;
}): {
    id: Principal;
    bio: string;
    lastProfileUpdate: Time;
    name: string;
    createdAt: Time;
    role: AppRole;
    registrationNumber?: string;
    email: string;
    hospitalId?: Principal;
    aadharNumber?: string;
    address: string;
    specialization?: string;
    phone: string;
    verificationStatus: VerificationStatus;
} {
    return {
        id: value.id,
        bio: value.bio,
        lastProfileUpdate: value.lastProfileUpdate,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_AppRole_n11(_uploadFile, _downloadFile, value.role),
        registrationNumber: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.registrationNumber)),
        email: value.email,
        hospitalId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.hospitalId)),
        aadharNumber: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.aadharNumber)),
        address: value.address,
        specialization: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.specialization)),
        phone: value.phone,
        verificationStatus: from_candid_VerificationStatus_n15(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contributedAt: _Time;
    userId: Principal;
    needId: string;
    amount: bigint;
    contributionType: {
        Clothes: null;
    } | {
        Money: null;
    } | {
        Essentials: null;
    };
}): {
    id: string;
    contributedAt: Time;
    userId: Principal;
    needId: string;
    amount: bigint;
    contributionType: Variant_Clothes_Money_Essentials;
} {
    return {
        id: value.id,
        contributedAt: value.contributedAt,
        userId: value.userId,
        needId: value.needId,
        amount: value.amount,
        contributionType: from_candid_variant_n7(_uploadFile, _downloadFile, value.contributionType)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n26(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    title: string;
    trustId: Principal;
    needType: {
        Clothes: null;
    } | {
        Money: null;
    } | {
        Essentials: null;
    };
    description: string;
    receivedAmount: bigint;
    targetAmount: bigint;
}): {
    id: string;
    status: string;
    title: string;
    trustId: Principal;
    needType: Variant_Clothes_Money_Essentials;
    description: string;
    receivedAmount: bigint;
    targetAmount: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        title: value.title,
        trustId: value.trustId,
        needType: from_candid_variant_n7(_uploadFile, _downloadFile, value.needType),
        description: value.description,
        receivedAmount: value.receivedAmount,
        targetAmount: value.targetAmount
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PublicUser: null;
} | {
    Doctor: null;
} | {
    Trust: null;
} | {
    Admin: null;
} | {
    Hospital: null;
}): AppRole {
    return "PublicUser" in value ? AppRole.PublicUser : "Doctor" in value ? AppRole.Doctor : "Trust" in value ? AppRole.Trust : "Admin" in value ? AppRole.Admin : "Hospital" in value ? AppRole.Hospital : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): VerificationStatus {
    return "Approved" in value ? VerificationStatus.Approved : "Rejected" in value ? VerificationStatus.Rejected : "Pending" in value ? VerificationStatus.Pending : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Clothes: null;
} | {
    Money: null;
} | {
    Essentials: null;
}): Variant_Clothes_Money_Essentials {
    return "Clothes" in value ? Variant_Clothes_Money_Essentials.Clothes : "Money" in value ? Variant_Clothes_Money_Essentials.Money : "Essentials" in value ? Variant_Clothes_Money_Essentials.Essentials : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contribution>): Array<Contribution> {
    return value.map((x)=>from_candid_Contribution_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonationNeed>): Array<DonationNeed> {
    return value.map((x)=>from_candid_DonationNeed_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_DonationNeed_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationNeed): _DonationNeed {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): _VerificationStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: string;
    lastProfileUpdate: Time;
    name: string;
    createdAt: Time;
    role: AppRole;
    registrationNumber?: string;
    email: string;
    hospitalId?: Principal;
    aadharNumber?: string;
    address: string;
    specialization?: string;
    phone: string;
    verificationStatus: VerificationStatus;
}): {
    id: Principal;
    bio: string;
    lastProfileUpdate: _Time;
    name: string;
    createdAt: _Time;
    role: _AppRole;
    registrationNumber: [] | [string];
    email: string;
    hospitalId: [] | [Principal];
    aadharNumber: [] | [string];
    address: string;
    specialization: [] | [string];
    phone: string;
    verificationStatus: _VerificationStatus;
} {
    return {
        id: value.id,
        bio: value.bio,
        lastProfileUpdate: value.lastProfileUpdate,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_AppRole_n28(_uploadFile, _downloadFile, value.role),
        registrationNumber: value.registrationNumber ? candid_some(value.registrationNumber) : candid_none(),
        email: value.email,
        hospitalId: value.hospitalId ? candid_some(value.hospitalId) : candid_none(),
        aadharNumber: value.aadharNumber ? candid_some(value.aadharNumber) : candid_none(),
        address: value.address,
        specialization: value.specialization ? candid_some(value.specialization) : candid_none(),
        phone: value.phone,
        verificationStatus: to_candid_VerificationStatus_n32(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    title: string;
    trustId: Principal;
    needType: Variant_Clothes_Money_Essentials;
    description: string;
    receivedAmount: bigint;
    targetAmount: bigint;
}): {
    id: string;
    status: string;
    title: string;
    trustId: Principal;
    needType: {
        Clothes: null;
    } | {
        Money: null;
    } | {
        Essentials: null;
    };
    description: string;
    receivedAmount: bigint;
    targetAmount: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        title: value.title,
        trustId: value.trustId,
        needType: to_candid_variant_n3(_uploadFile, _downloadFile, value.needType),
        description: value.description,
        receivedAmount: value.receivedAmount,
        targetAmount: value.targetAmount
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    PublicUser: null;
} | {
    Doctor: null;
} | {
    Trust: null;
} | {
    Admin: null;
} | {
    Hospital: null;
} {
    return value == AppRole.PublicUser ? {
        PublicUser: null
    } : value == AppRole.Doctor ? {
        Doctor: null
    } : value == AppRole.Trust ? {
        Trust: null
    } : value == AppRole.Admin ? {
        Admin: null
    } : value == AppRole.Hospital ? {
        Hospital: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Clothes_Money_Essentials): {
    Clothes: null;
} | {
    Money: null;
} | {
    Essentials: null;
} {
    return value == Variant_Clothes_Money_Essentials.Clothes ? {
        Clothes: null
    } : value == Variant_Clothes_Money_Essentials.Money ? {
        Money: null
    } : value == Variant_Clothes_Money_Essentials.Essentials ? {
        Essentials: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
} {
    return value == VerificationStatus.Approved ? {
        Approved: null
    } : value == VerificationStatus.Rejected ? {
        Rejected: null
    } : value == VerificationStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
